Algoritmo "lacoparaincremento"
// Disciplina  : Programação e Algorítimos
// Professor   : Cintia Pinho
// Descrição   : serve como um contador
// Autor(a)    : Ana Luiza de Oliveira Ferreira
// Data atual  : 24/08/2020
Var
// Seção de Declarações das variáveis 
x, total, qtde: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("*.·-LAÇO PARA - INCREMENTO-·.*")
para x de 1 ate 20 passo 1 faca
     escreval(x)
fimpara

Fimalgoritmo